---
- name: Create a virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup }}"
    name: "{{ virtualnetwork_name }}"
    address_prefixes_cidr:
        - "{{ cidr }}"
    tags:
        project: "tag_project"
        owner: "tag_owner"

- name: Create a subnet
  azure_rm_subnet:
    resource_group: "{{ resourcegroup }}"
    virtual_network_name: "{{ virtualnetwork_name }}"
    name: "{{ subnet_name }}"
    address_prefix_cidr: "{{ subnet_cidr }}"
